routes/web.php
<?php

use App\EXRX;
use App\User;
use GuzzleHttp\Psr7;
use App\Jobs\SendEmail;
use App\Jobs\SendEmailTest;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Response;
use GuzzleHttp\Exception\RequestException;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('testing' , 'AdminController@notific');

Route::get('/', function () {
    // dd('sad');
    return view('welcome');
    // return redirect()->route('login');
})->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('get/notifications/{user_id}', 'HomeController@getNotifications')->name('get.notifications');


Route::get('/homepage', 'HomeController@homepage')->name('homepage');

Route::group(['prefix' => 'admin' , 'as' => 'admin.', 'middleware'=>['auth','admin']  ], function () {
    Route::get('/' , function(){
            return redirect('/admin/dashboard');
    } );
    Route::get('/dashboard' , 'DashboardController@index' )->name('index');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('dietitian', 'DietitianController');

    Route::resource('coach', 'CoachController');
    
    Route::get('coach/{coach_id}/clients/' , 'CoachController@viewClients' )->name('coach.clients') ;
    Route::get('coach/{coach_id}/client/{clinet_id}/all-packages' , 'CoachController@viewClientPackages' )->name('coach.client.packages') ;

    Route::get('coach/{coach_id}/client/{clinet_id}/package/{package_id}/plan/view' , 'CoachController@viewClientPackagePlan' )->name('coach.client.package.plan.view') ;

    Route::resource('trainer', 'TrainerController');
    Route::resource('questionnaires', 'QuestionnaireController');
    Route::get('questionnaires/{id}/assignedto','QuestionnaireController@assignedto')->name('question.assigned');
    Route::get('questionnaires/{id}/coach/{coach_id}/show','QuestionnaireController@showCoachAnswers')->name('question.coach.show');
    Route::resource('packages', 'PackageController');
    Route::get('packages/{id}/assignedto','PackageController@assignedto')->name('package.assigned');
    Route::resource('tags', 'TagController');
    Route::resource('supplements','SupplementController');
    Route::resource('workouts','WorkoutController');
    Route::get('user/export','UserController@userExport')->name('export.user');

    Route::get('/messages/{reciever?}' , 'DashboardController@showMessages')->name('messages');
    Route::get('/contact' , 'DashboardController@editContactUS')->name('contact');
    Route::post('/contact/update' , 'DashboardController@updateContactUS')->name('contact.update');
    
    
    Route::get('/financial-reports' , 'FinancialReportsController@getReportForAdmin')->name('financial-reports');
    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPayments')->name('financial-reports.filter');

    Route::get('/pay-to-coach/{payment_id}' , 'FinancialReportsController@payToCoach')->name('pay-to-coach');
    Route::get('/remove/pay-to-coach/{payment_id}' , 'FinancialReportsController@removePayToCoach')->name('remove.pay-to-coach');
    


    Route::get('/exports/payments/{client_ids}' , 'FinancialReportsController@exportPayments')->name('export.payments');


    Route::get('/clients/exports/{client_ids}' , 'DashboardController@exportClients')->name('clients.export');

    // Route::get('/dietitian' , 'DietitianController@index' )->name('dietitian');
});



Route::post('/verifyusername', 'UserController@verifyUserName')->name('verify.username');
Route::post('verifyemail','UserController@verifyEmail')->name('verify.email');
Route::get('tagnames','TagController@tagnames')->name('tagnames');

// ajax routes
Route::get('/change/user/status/{user_id}' , 'UserController@changeStatus' );
















Route::get('coach/login' , 'CoachDashboardController@login' )->name('coach.login');

Route::group(['prefix' => 'coach' , 'as' => 'coach.' , 'middleware'=>['auth' , 'coach']   ], function () {
    Route::get('/' , 'CoachDashboardController@index' )->name('index');
    Route::get('profile' , 'CoachDashboardController@showProfile' )->name('profile');
    // Route::get('profile/edit' , 'CoachDashboardController@editProfile' )->name('profile.edit');
    Route::post('profile/update/{id}' , 'CoachDashboardController@updateProfile' )->name('profile.update');

    Route::get('dashboard' , 'CoachDashboardController@index' )->name('dashboard');
    Route::get('packages' , 'CoachDashboardController@showPackages' )->name('packages');
    Route::get('packages/view/{id}' , 'CoachDashboardController@viewPackage' )->name('packages.view');

    Route::get('questionnaires' , 'CoachDashboardController@showQuestionnaires' )->name('questionnaires');
    Route::get('questionnaires/view/{id}' , 'CoachDashboardController@showQuestionnaire' )->name('questionnaires.view');
    Route::post('questionnaires/store-answer/{id}' , 'QuestionnaireController@storeAnswer' )->name('questionnaires.store-answer');
    

    Route::get('manage-clients' , 'CoachDashboardController@showClients' )->name('manage-clients');
    
    Route::get('manage-clients/filter' , 'CoachDashboardController@filterClients' )->name('manage-clients.filter');
    
    Route::get('manage-client/{client_id}/all-packages' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');
    
    
    Route::post('manage-client/{client_id}/handle-client-request' , 'CoachDashboardController@handleClientRequest' )->name('manage-client.handle-client-request');


    Route::get('manage-client/{client_id}/details' , 'CoachDashboardController@showClientDetails' )->name('manage-client.details');

    Route::get('manage-client/{client_id}/package/{package}/create-plan' , 'CoachDashboardController@createClientPlan' )->name('manage-client.package.create-plan');
    
    
    Route::get('manage-client/{client_id}/package/{package}/start-plan' , 'CoachDashboardController@startClientPlan' )->name('manage-client.package.start-plan');
    
    Route::get('/messages/{reciever?}' , 'CoachDashboardController@showMessages')->name('messages');

    Route::get('/view/workout/{id}' , 'CoachDashboardController@showWorkout' )->name('view.workout');


    Route::get('/financial-reports' , 'FinancialReportsController@getReportForCoach')->name('financial-reports');

    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPaymentsCoach')->name('financial-reports.filter');

    Route::get('reviews' , 'CoachDashboardController@showReviews' )->name('reviews');

    Route::resource('client-questionnaires' , 'ClientQuestionnaireController' );
    Route::post('client-questionnaires-update' , 'ClientQuestionnaireController@update' );
    Route::get('client-questionnaires/{questionnaires_id}/assigned-clients' , 'ClientQuestionnaireController@clients' )->name('client-questionnaires.assigned-clients');
    Route::get('client-questionnaires-delete/{questionnaires_id}' , 'ClientQuestionnaireController@destroy');
    
    Route::post('send-questionnaires-client' , 'ClientQuestionnaireController@sendQuestionnaireToClient');
    
    Route::get('client/{client_id}/questionnaires/{questionnaires_id}/show' , 'ClientQuestionnaireController@showAnswer')->name('client.questionnaires.show') ;

    Route::get('get-questionnaires' , 'ClientQuestionnaireController@getQuestionnaires') ;

    // Route::get('manage-client/{client_id}/package/{package}/plan/{plan}' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');


});


Route::get('/exports/clients/{client_ids}/{coach}' , 'HomeController@exportClients')->name('export.clients');











Route::get('local_payment/{plan_id}'  , 'Api\ClientPaymentController@makePayment' )->name('local_payment') ;
Route::get('remove_local_payment/{payment_id}'  , 'Api\ClientPaymentController@removePayment' )->name('remove_local_payment') ;



// Route::get('paypal' ,  'Api\ApiPlanController@PayForPlan2' );
Route::get('sadad' ,  'Api\ApiPlanController@PayWithSadad' );
Route::get('payment' ,  'PaypalPaymentController@braintreePayment' );
// Route::get('paypal' ,  'PaypalPaymentController@payment' );
// Route::get('paypal' ,  'PaypalPaymentController@paywithCreditCard' );
// Route::get('paypal' ,  'PaypalPaymentController@PayumPayment' );
// Route::post('stripe' ,  'Api\ApiPlanController@PayForPlanStripe' );
// Route::post('stripe-mobile' ,  'Api\ApiPlanController@PayForPlanStripe1' );
Route::get('brain' , 'Api\ApiPlanController@make' );


// Route::get('paypal' , 'Api\ApiPlanController@payForPlan2' );
Route::get('paypal_web' , 'Api\ApiPlanController@paypalWeb' );
Route::get('paypal_return' , 'Api\ApiPlanController@paypalReturn' );

// Route::get('paypal' , function(){


//     $gateway = new Braintree\Gateway([
//         'environment' => 'sandbox',
//         'merchantId' => env('BRAINTREE_MERCHANT_ID'),
//         'publicKey' => env('BRAINTREE_PUBLIC_KEY'),
//         'privateKey' => env('BRAINTREE_PRIVATE_KEY')
//     ]);

//     // $clientToken = $gateway->clientToken()->generate([
//     //     "customerId" => 11
//     // ]);
//     $clientToken = $gateway->clientToken()->generate();

//     // dd($clientToken);

//     return view('coach\clients\payment' , compact('clientToken'));
// } );

Route::get("/payment/make" , 'Api\ApiPlanController@make')->name('payment.make');


Route::get('stripe' , 'Api\ApiPlanController@PayForPlanStripe1' );

Route::get('success' , function(){
    dd('success');
});

Route::get('fail' , function(){

app/Questionnaire.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Questionnaire extends Model
{
    //

    protected $guarded = [];

    public function users(){
        return $this->belongsToMany('App\User' , 'assigned_questionaires' , 'question_id' , 'user_id');
    }

    public function questions(){
        return $this->hasMany('App\Question','questionnaires_id','id')->orderBy('created_at' , 'asc');
    }
}

resources/views/admin/questionnaires/assignedto.blade.php
@extends('layouts.dashboard')


@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title"><b>{{$question->question}}</b> Questionnaire Assigne To</h3>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>User Name</th>
                            <th>Email</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(isset($question))
                            @foreach($question->users as $k=> $user)
                                <tr>
                                    <td>{{$k+1}}</td>
                                    <td> {{$user->name}} </td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->role->name}}</td>
                                    <td>
                                        <a href="{{route('admin.question.coach.show' , [$question->id , $user->coach->id])}}" class="btn btn-sm btn-primary">View</a>
                                    </td>
                                </tr>
                        </tbody>
                        @endforeach
                        @endif
                    </table>
                </div>
            </div>

        </div>
    </div>

@endsection

@section('scripts')
    <script>

    </script>
@endsection

resources/views/admin/questionnaires/create.blade.php
@extends('layouts.dashboard')



@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" >
    <div class="card card-info ">
      <div class="card-header">
        <h3 class="card-title">Create Questionnaire</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <form action="{{route('admin.questionnaires.store')}}" method="POST">
        @include('layouts.partials.form_errors')

          @csrf

          <div class="form-group row">
            <div class="col-sm-2">
            <label for="questionnaire" class="row float-right col-form-label ">Questionnaire:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="questionnaire" placeholder="Name" name="questionnaire" value="{{old('questionnaire')}}" required>
            </div>
              <div class="col-sm-2">
                  <button type="button"style="height: 35px;  " id="add_question"  onclick="add_new_question()" class="btn btn-outline-success"> <i class="fas fa-plus"></i> </button>

              </div>
          </div>

          <div id="question_area">
              <div id="choices_area">


                  {{-- <div id="choice" class="form-group row">
                    <div class="col-sm-3">
                    <label class="row float-right col-form-label ">Choice:</label>
                  </div>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" placeholder="Choice" name="choice[]" value="" required>

                    </div>

                    <div  class="col-sm-2">
                        <button onclick="remove_row()" style="height: 35px;" class="btn btn-outline-danger" type="button" > <i class="fas fa-minus"></i> </button>
                    </div>

                  </div> --}}

              </div>


          </div>
          
       <!--   <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Type:</label>
          </div>
            <div class="col-sm-8">
              <select class="form-control" id="question_type" name="type" onchange="toggle_choices()" >
                  <option value="text" selected >Text</option>
                  <option value="checkbox">CheckBoxes</option>
                  <option value="radiobutton">RadioButtons</option>
              </select>
            </div>
            <div class="col-sm-2">
                <button type="button"style="height: 35px; display:none; " id="add_button"  onclick="add_new_row()" class="btn btn-outline-success"> <i class="fas fa-plus"></i> </button>
            </div>
          </div>-->
          
          


        <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Assign To:</label>
          </div>
            <div class="col-sm-8">
                <select class="select2bs4" multiple style="width: 100%;height: 40px;" name="assigned[]" >
                    @foreach($users as $user)
                    <option value="{{$user->id}}" >{{$user->name}}</option>
                    @endforeach
                </select>
                </div>
        
          </div>

        
        <div>
            <button class="btn btn-primary float-right" onclick="beforeSubmit();">Create</button>
        </div>
      </form>
    </div>
    </div>
  
  </div>
</div>

@endsection



@section('scripts')
    <script>

        function reIndex(){
            $('.question').each(function (k,v) {
               $(this).children('.row').children('.col-sm-6').children('#question').attr('name', 'question['+k+'][name]');
               $(this).children('.row').children('.col-sm-6').children('.question_type').attr({'name':'question['+k+'][type]','id':'question_type'+k+'','onChange':'toggle_choices('+k+')'});
                $(this).children('.row').children('.col-sm-2').children('button').attr({'id':'add_button'+k+'', 'onClick':'add_new_row('+k+')'});
                $(this).children('.row').children('.col-sm-4').children('.choice').attr({'name':'question['+k+'][choices][]'});
            });
        }
        var i = 0;
        function add_new_row(id){
            i += 1;

            $('#question-'+id).append('<div id="choice-'+i+'" class="form-group row "> <div class="col-sm-4"> <label class="row float-right col-form-label ">Choice :</label> </div> <div class="col-sm-4"> <input type="text" class="form-control choice" placeholder="Choice" name="question['+id+'][choices][]" required>  </div>  <div  class="col-sm-2"> <button onclick="remove_row(this.id)" id="'+i+'" type="button" style="height: 35px;" class="btn btn-outline-danger"> <i class="fas fa-minus"></i> </button> </div> </div>')
        }
        
        function remove_row(row_id){
            $('#choice-'+row_id).remove();
        }
        function toggle_choices(question_id){
            if($('#question_type'+question_id).val() == 'text' ){
                $('#choices_area div').remove();
                $('#add_button').hide();
                i = 0;

            }else{
                $('#add_button'+question_id).show();
            }
        }


        var question = 0;
        function add_new_question() {
            question+=1;

            $('#question_area').append('<div id="question-'+question+'" class="question" > <div class="form-group row"> <div class="col-sm-3"><label for="question" class="row float-right col-form-label ">Question '+question+':</label></div>\n' +
                '<div class="col-sm-6"><input type="text" class="form-control" id="question" placeholder="Name" name="question['+question+'][name]" value="" required></div> ' +
                    '<div  class="col-sm-2"> <button onclick="remove_question(this.id);" id="'+question+'" type="button" style="height: 35px;" class="btn btn-outline-danger"> <i class="fas fa-minus"></i> </button> </div> </div>'+
                '<div class="form-group row">\n' +
                '<div class="col-sm-3">\n' +
                '<label for="inputEmail1" class="row float-right col-form-label ">Type:</label>\n' +
                '</div>\n' +
                '<div class="col-sm-6">\n' +
                '     <select class="form-control question_type" id="question_type'+question+'" name="question['+question+'][type]" onchange="toggle_choices('+question+')" >\n' +
                '            <option value="text" selected >Text</option>\n' +
                '            <option value="checkbox">CheckBoxes</option>\n' +
                '             <option value="radiobutton">RadioButtons</option>\n' +
                '      </select>\n' +
                '</div>\n' +
                '<div class="col-sm-2">\n' +
                '     <button type="button"style="height: 35px; display:none; " id="add_button'+question+'"  onclick="add_new_row('+question+')" class="btn btn-outline-success"> <i class="fas fa-plus"></i> </button>\n' +
                ' </div>\n' +
                ' </div></div>\n' +
                '          ')

            
        }

        function remove_question(question_id) {

            $('#question-'+question_id).remove();
        }

        
        function beforeSubmit() {

            reIndex();
            $('#form-submit').submit();
            
        }


    </script>
@endsection

resources/views/admin/questionnaires/create_new.blade.php
@extends('layouts.dashboard')



@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" id="vue" >
    <div class="card card-info ">
      <div class="card-header">
        <h3 class="card-title">Create Questionnaire</h3>
      </div>
      <!-- /.card-header -->
        <div style="padding:30px" >
          {{--  @dd($questionnaire->users)  --}}
            <question-element 
                @if(isset($questionnaire)) :current_questionnaire="{{$questionnaire}}" @endif
                @if(isset($questionnaire->questions)) :current_questions="{{$questionnaire->questions}}" @endif
                @if(isset($users)) :users="{{$users}}" @endif
                @if(isset($questionnaire->users)) :current_users="{{$questionnaire->users}}" @endif
              
              ></question-element>
        </div>
    </div>
  
  </div>
</div>

@endsection



@section('scripts')
    <script>
    </script>
@endsection

resources/views/admin/questionnaires/index.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" >
    <div class="card ">
      <div class="card-header">
        <h3 class="card-title">Manage Questionnaire</h3>
        {{--  <h3 class="card-title">Manage Questionnaires</h3>  --}}
        <a class="btn btn-outline-primary float-right" href="{{route('admin.questionnaires.create')}}"> <i class="fas fa-plus"></i> Create</a>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <table class="table">
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Assign To</th>
              <th>Create Date</th>
              <th>Actions</th>
          </tr>
          @if(isset($questions))
          @foreach($questions as $k => $question)
          <tr>
              <td> {{$k+1}} </td>
              <td> {{$question->name}} </td>
              <td><a class="btn btn-sm btn-success" href="{{route('admin.question.assigned', $question->id)}}"> View ({{$question->users()->count()}}) </a></td>
              <td> {{$question->created_at->format('m/d/Y') }} </td>
              <td>
                
                {{-- <div class="icheck-success d-inline">
                    <input onchange="change_user_status({{$question->user->id}})" type="checkbox" @if($question->user->status == 1) checked @endif id="checkboxSuccess{{$question->user->id}}">
                    <label for="checkboxSuccess{{$question->user->id}}">
                    </label>
                  </div> --}}

                  <a href="javascript:;" onclick="AskBeforeDelete({{$question->id}})" class="text-danger"  > <i class="fas fa-trash"></i> </a>

                  <a href="{{route('admin.questionnaires.edit' , $question->id)}}" > <i class="fas fa-edit"></i> </a>

                  <a href="{{route('admin.questionnaires.show' , $question->id)}}" class="btn btn-sm btn-primary" > <i class="fas fa-eye"></i> View</a>


              </td>

              <form id="delete-form-{{$question->id}}" action="{{route('admin.questionnaires.destroy' , $question->id)}}" method="POST" >
                  @csrf
                  @method('DELETE')
              </form>
          </tr>
          @endforeach
          @endif
      </table>
    </div>
    </div>
  
  </div>
</div>

@endsection

@section('scripts')
    <script>
        function AskBeforeDelete(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
              }).then((result) => {
                if (result.value) {
                  
                    $('#delete-form-'+id).submit();
                }
              })
        }

        function change_user_status(id){
            $.ajax({
                url: '{{url("/")}}/change/user/status/'+id,
                success: function (res){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'User Status Has been updated',
                        showConfirmButton: false,
                        timer: 1500
                      })
                }
            }).fail(function(){
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Some Problem occured',
                    showConfirmButton: false,
                    timer: 1500
                  })
            })
        }
    </script>
@endsection

resources/views/admin/questionnaires/showAnswer.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')


   <div class="col-md-12" style="padding:30px" >
    <div class="card card-info ">
      <div class="card-header">
        <h3 class="card-title">Answered By {{$coach->user->name}}</h3>
      </div>
      <!-- /.card-header -->
        <div style="padding:30px" >
      <h4>{{$questionnaire->name}}</h4>
        <div>
        @foreach($questionnaire->questions as $k => $question)
        @php
        $answer = $question->answer($coach->id);
        @endphp
        {{-- dump($question->id , $question->answers); --}}

        {{-- @dump($answer) --}}
        <input type="hidden" name="questions[]" value="{{$question->id}}" >

        <div class="ml-3">
        <label class="col-form-label">Q {{$k+1}} : {{$question->question}} </label>
        <p class="float-right">{{ isset($answer) ? $answer->updated_at->toDateString() : "-"}} </p>
        
        <div>
            {{-- @dd($question->answer(auth()->user()->coach->id)) --}}
            @if($question->type == 'text')
            <textarea class="form-control" disabled >{{ isset($answer) && !is_array(json_decode($answer->answer)) ? $answer->answer : ""}}</textarea>
            @endif
        </div>
        @if($question->type == 'checkbox')
        <div>
            @foreach($question->choices as $k => $choice)
            
            <input name="question-{{$question->id}}[]" id="question-{{$question->id}}-{{$choice->id}}" class="ml-5" value="{{$choice->name}}"  type="checkbox" 
            {{-- @dd(json_decode($question->answer(auth()->user()->coach->id)->answer)[$k] == $choice->name) --}}
            @if($answer && is_array(json_decode($answer->answer)) && in_array( $choice->name , json_decode($answer->answer) ) )
            checked
            @endif
            disabled
            />
            <label  for="question-{{$question->id}}-{{$choice->id}}" class=" col-form-label">{{$choice->name}}</label>
            <br>
            @endforeach
    
        </div>
        @endif
        @if($question->type == 'radiobutton')
        <div>
            @foreach($question->choices as $choice)

            <input name="question-{{$question->id}}" id="question-{{$question->id}}-{{$choice->id}}" class="ml-5" value="{{$choice->name}}" type="radio" 
            @if($answer && $answer->answer == $choice->name)
            checked
            @endif
            disabled
            />
            <label for="question-{{$question->id}}-{{$choice->id}}" class=" col-form-label">{{$choice->name}}</label>
            <br>
            @endforeach
    
        </div>
        @endif
    </div>
    <hr>
        @endforeach
    </div>
    </div>
    </div>
  
  </div>
</div>

@endsection