routes/web.php
<?php

use App\EXRX;
use App\User;
use GuzzleHttp\Psr7;
use App\Jobs\SendEmail;
use App\Jobs\SendEmailTest;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Response;
use GuzzleHttp\Exception\RequestException;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('testing' , 'AdminController@notific');

Route::get('/', function () {
    // dd('sad');
    return view('welcome');
    // return redirect()->route('login');
})->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('get/notifications/{user_id}', 'HomeController@getNotifications')->name('get.notifications');


Route::get('/homepage', 'HomeController@homepage')->name('homepage');

Route::group(['prefix' => 'admin' , 'as' => 'admin.', 'middleware'=>['auth','admin']  ], function () {
    Route::get('/' , function(){
            return redirect('/admin/dashboard');
    } );
    Route::get('/dashboard' , 'DashboardController@index' )->name('index');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('dietitian', 'DietitianController');

    Route::resource('coach', 'CoachController');
    
    Route::get('coach/{coach_id}/clients/' , 'CoachController@viewClients' )->name('coach.clients') ;
    Route::get('coach/{coach_id}/client/{clinet_id}/all-packages' , 'CoachController@viewClientPackages' )->name('coach.client.packages') ;

    Route::get('coach/{coach_id}/client/{clinet_id}/package/{package_id}/plan/view' , 'CoachController@viewClientPackagePlan' )->name('coach.client.package.plan.view') ;

    Route::resource('trainer', 'TrainerController');
    Route::resource('questionnaires', 'QuestionnaireController');
    Route::get('questionnaires/{id}/assignedto','QuestionnaireController@assignedto')->name('question.assigned');
    Route::get('questionnaires/{id}/coach/{coach_id}/show','QuestionnaireController@showCoachAnswers')->name('question.coach.show');
    Route::resource('packages', 'PackageController');
    Route::get('packages/{id}/assignedto','PackageController@assignedto')->name('package.assigned');
    Route::resource('tags', 'TagController');
    Route::resource('supplements','SupplementController');
    Route::resource('workouts','WorkoutController');
    Route::get('user/export','UserController@userExport')->name('export.user');

    Route::get('/messages/{reciever?}' , 'DashboardController@showMessages')->name('messages');
    Route::get('/contact' , 'DashboardController@editContactUS')->name('contact');
    Route::post('/contact/update' , 'DashboardController@updateContactUS')->name('contact.update');
    
    
    Route::get('/financial-reports' , 'FinancialReportsController@getReportForAdmin')->name('financial-reports');
    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPayments')->name('financial-reports.filter');

    Route::get('/pay-to-coach/{payment_id}' , 'FinancialReportsController@payToCoach')->name('pay-to-coach');
    Route::get('/remove/pay-to-coach/{payment_id}' , 'FinancialReportsController@removePayToCoach')->name('remove.pay-to-coach');
    


    Route::get('/exports/payments/{client_ids}' , 'FinancialReportsController@exportPayments')->name('export.payments');


    Route::get('/clients/exports/{client_ids}' , 'DashboardController@exportClients')->name('clients.export');

    // Route::get('/dietitian' , 'DietitianController@index' )->name('dietitian');
});



Route::post('/verifyusername', 'UserController@verifyUserName')->name('verify.username');
Route::post('verifyemail','UserController@verifyEmail')->name('verify.email');
Route::get('tagnames','TagController@tagnames')->name('tagnames');

// ajax routes
Route::get('/change/user/status/{user_id}' , 'UserController@changeStatus' );
















Route::get('coach/login' , 'CoachDashboardController@login' )->name('coach.login');

Route::group(['prefix' => 'coach' , 'as' => 'coach.' , 'middleware'=>['auth' , 'coach']   ], function () {
    Route::get('/' , 'CoachDashboardController@index' )->name('index');
    Route::get('profile' , 'CoachDashboardController@showProfile' )->name('profile');
    // Route::get('profile/edit' , 'CoachDashboardController@editProfile' )->name('profile.edit');
    Route::post('profile/update/{id}' , 'CoachDashboardController@updateProfile' )->name('profile.update');

    Route::get('dashboard' , 'CoachDashboardController@index' )->name('dashboard');
    Route::get('packages' , 'CoachDashboardController@showPackages' )->name('packages');
    Route::get('packages/view/{id}' , 'CoachDashboardController@viewPackage' )->name('packages.view');

    Route::get('questionnaires' , 'CoachDashboardController@showQuestionnaires' )->name('questionnaires');
    Route::get('questionnaires/view/{id}' , 'CoachDashboardController@showQuestionnaire' )->name('questionnaires.view');
    Route::post('questionnaires/store-answer/{id}' , 'QuestionnaireController@storeAnswer' )->name('questionnaires.store-answer');
    

    Route::get('manage-clients' , 'CoachDashboardController@showClients' )->name('manage-clients');
    
    Route::get('manage-clients/filter' , 'CoachDashboardController@filterClients' )->name('manage-clients.filter');
    
    Route::get('manage-client/{client_id}/all-packages' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');
    
    
    Route::post('manage-client/{client_id}/handle-client-request' , 'CoachDashboardController@handleClientRequest' )->name('manage-client.handle-client-request');


    Route::get('manage-client/{client_id}/details' , 'CoachDashboardController@showClientDetails' )->name('manage-client.details');

    Route::get('manage-client/{client_id}/package/{package}/create-plan' , 'CoachDashboardController@createClientPlan' )->name('manage-client.package.create-plan');
    
    
    Route::get('manage-client/{client_id}/package/{package}/start-plan' , 'CoachDashboardController@startClientPlan' )->name('manage-client.package.start-plan');
    
    Route::get('/messages/{reciever?}' , 'CoachDashboardController@showMessages')->name('messages');

    Route::get('/view/workout/{id}' , 'CoachDashboardController@showWorkout' )->name('view.workout');


    Route::get('/financial-reports' , 'FinancialReportsController@getReportForCoach')->name('financial-reports');

    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPaymentsCoach')->name('financial-reports.filter');

    Route::get('reviews' , 'CoachDashboardController@showReviews' )->name('reviews');

    Route::resource('client-questionnaires' , 'ClientQuestionnaireController' );
    Route::post('client-questionnaires-update' , 'ClientQuestionnaireController@update' );
    Route::get('client-questionnaires/{questionnaires_id}/assigned-clients' , 'ClientQuestionnaireController@clients' )->name('client-questionnaires.assigned-clients');
    Route::get('client-questionnaires-delete/{questionnaires_id}' , 'ClientQuestionnaireController@destroy');
    
    Route::post('send-questionnaires-client' , 'ClientQuestionnaireController@sendQuestionnaireToClient');
    
    Route::get('client/{client_id}/questionnaires/{questionnaires_id}/show' , 'ClientQuestionnaireController@showAnswer')->name('client.questionnaires.show') ;

    Route::get('get-questionnaires' , 'ClientQuestionnaireController@getQuestionnaires') ;

    // Route::get('manage-client/{client_id}/package/{package}/plan/{plan}' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');


});


Route::get('/exports/clients/{client_ids}/{coach}' , 'HomeController@exportClients')->name('export.clients');











Route::get('local_payment/{plan_id}'  , 'Api\ClientPaymentController@makePayment' )->name('local_payment') ;
Route::get('remove_local_payment/{payment_id}'  , 'Api\ClientPaymentController@removePayment' )->name('remove_local_payment') ;



// Route::get('paypal' ,  'Api\ApiPlanController@PayForPlan2' );
Route::get('sadad' ,  'Api\ApiPlanController@PayWithSadad' );
Route::get('payment' ,  'PaypalPaymentController@braintreePayment' );
// Route::get('paypal' ,  'PaypalPaymentController@payment' );
// Route::get('paypal' ,  'PaypalPaymentController@paywithCreditCard' );
// Route::get('paypal' ,  'PaypalPaymentController@PayumPayment' );
// Route::post('stripe' ,  'Api\ApiPlanController@PayForPlanStripe' );
// Route::post('stripe-mobile' ,  'Api\ApiPlanController@PayForPlanStripe1' );
Route::get('brain' , 'Api\ApiPlanController@make' );


// Route::get('paypal' , 'Api\ApiPlanController@payForPlan2' );
Route::get('paypal_web' , 'Api\ApiPlanController@paypalWeb' );
Route::get('paypal_return' , 'Api\ApiPlanController@paypalReturn' );

// Route::get('paypal' , function(){


//     $gateway = new Braintree\Gateway([
//         'environment' => 'sandbox',
//         'merchantId' => env('BRAINTREE_MERCHANT_ID'),
//         'publicKey' => env('BRAINTREE_PUBLIC_KEY'),
//         'privateKey' => env('BRAINTREE_PRIVATE_KEY')
//     ]);

//     // $clientToken = $gateway->clientToken()->generate([
//     //     "customerId" => 11
//     // ]);
//     $clientToken = $gateway->clientToken()->generate();

//     // dd($clientToken);

//     return view('coach\clients\payment' , compact('clientToken'));
// } );

Route::get("/payment/make" , 'Api\ApiPlanController@make')->name('payment.make');


Route::get('stripe' , 'Api\ApiPlanController@PayForPlanStripe1' );

Route::get('success' , function(){
    dd('success');
});

Route::get('fail' , function(){

app/Dietitian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dietitian extends Model
{
    protected $guarded = [];


    public function user(){
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/DietitianController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\User;
use App\Dietitian;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class DietitianController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dietitians = Dietitian::with('user')->get();
        return view('admin.dietitians.index' , compact('dietitians'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        return view('admin.dietitians.create',compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'username' => 'required|unique:users,username',
            'email' => 'required|email|unique:users,email',
            'password' => 'required ',
            'percentage' => 'numeric|min:0|max:100',
            ]);
        
            
            
        // dd($request->all());

        if($request->password != $request->conf_password ){
            return redirect()->back()->with('error' , 'Password does not match');
        }

        $user = User::create([
            'role_id' => 4,
            'name' => $request->name,
            'username' => $request->get('username'),
            'email' => $request->email,
            'password' => \Hash::make($request->password),

        ]);


        $user->tags()->attach($request->tags);

        if($user){
        $dietitian = Dietitian::create([
            'user_id' => $user->id,
            'phone' => $request->phone,
            'portfolio' => $request->portfolio,
            'percentage' => $request->percentage,
            // 'tags' => $request->tags,
            ]);

        if($dietitian){
            $data['msg'] = 'Hi '.$user->name . '<br>Welcome To FTBLE. <br> You have been registered as a Dietitian. <br> <b>Your account credentials are</b> <br> <b>Email:</b>'.$user->email.'<br> <b>Password:</b>'.$request->password ;
            
            \Mail::send('mails.general', $data, function ($message) use ($user) {
                $message->from('Info@FTBLE.com', 'FTBLE');
                // $message->sender('john@johndoe.com', 'John Doe');
                $message->to($user->email, $user->name);
            
                $message->subject('Welcome To FTBLE');
            
                // $message->priority(3);            
                // $message->attach('pathToFile');
            });            
        }



        if($request->has('image')){

            $ext = $request->image->getClientOriginalExtension();
            
            $request->image->move(public_path().'/images/profile_images/' , $user->id .'.'. $ext);
            $user->photo = $user->id .'.'. $ext;
            
            $user->save();
        }
        }



        if($user)
            return redirect('/admin/dietitian')->with('success' , 'Dietitian created successfully');
        else
            return redirect()->back()->with('error' , 'Some problem occured');
        
    }   

    /**
     * Display the specified resource.
     *
     * @param  \App\Dietitian  $dietitian
     * @return \Illuminate\Http\Response
     */
    public function show(Dietitian $dietitian)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dietitian  $dietitian
     * @return \Illuminate\Http\Response
     */
    public function edit(Dietitian $dietitian)
    {
        // $dietitian = Dietitian::with('user')->get();
        $tags = Tag::all();

        return view('admin.dietitians.edit' , compact('dietitian' , 'tags'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dietitian  $dietitian
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dietitian $dietitian)
    {
        // dd($request->all());

        $request->validate([
            'name' => 'required',
            'username' => 'sometimes',
            'email' => 'required|email',
            'password' => 'sometimes ',
            'percentage' => 'numeric|min:0|max:100',

        ]);
            // dd($request->all());

        if( isset($request->password) && $request->password != $request->conf_password ){
            return redirect()->back()->with('error' , 'Password does not match');
        }

        $user = User::findOrFail($dietitian->user_id);
            $user->name = $request->name;
            $user->username = $request->get('username');
            $user->email = $request->email;
            if($request->password){
                $user->password = \Hash::make($request->password);
            }
            $user->save();

            $user->tags()->sync($request->tags);
            
            $dietitian->user_id = $user->id;
            $dietitian->phone = $request->phone;
            $dietitian->portfolio = $request->portfolio;
            $dietitian->percentage = $request->percentage;
            // $dietitian->tags = $request->tags;

            
            if($request->has('image')){
                $path = public_path().'/images/profile_images/'.$user->photo;

                if(file_exists($path)){
                        File::delete($path);
                    }
                    $ext = $request->image->getClientOriginalExtension();
            
                    $request->image->move(public_path().'/images/profile_images/' , $user->id .'.'. $ext);
                    $user->photo = $user->id .'.'. $ext;
                    
                    $user->save();

                }

            $dietitian->save();


        if($user)
            return redirect('/admin/dietitian')->with('success' , 'Dietitian updated successfully');
        else
            return redirect()->back()->with('error' , 'Some problem occured');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dietitian  $dietitian
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dietitian $dietitian)
    {
        $user = User::find($dietitian->user_id);
        
        $path = public_path().'/images/dietitians/'.$dietitian->photo;
        if(file_exists($path)){
            File::delete($path);
        }

        $dietitian->delete();
        $user->delete();

        return redirect()->back()->with('success'  , 'Dietitian deleted successfully');
    }
}

resources/views/admin/dietitians/edit.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" >
    <div class="card card-info ">
      <div class="card-header">
        <h3 class="card-title">Update Dietitian</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <form action="{{route('admin.dietitian.update' , $dietitian->id)}}" method="POST" enctype="multipart/form-data" >
        @include('layouts.partials.form_errors')
        @method('PATCH')
          @csrf

        {{--  @dd($dietitian)  --}}
            <div class="form-group row">
            <div class="col-sm-2">
          </div>
            <div class="col-sm-8">
  
              <img id="image" src="@if($dietitian->user->photo) {{asset('images/profile_images/'.$dietitian->user->photo)}} @else {{asset('img/no-image-found.jpg')}} @endif" class="profile-image" />
  
              <button type="button" class="btn btn-outline-success" id="upload-button"> <i class="fas fa-image"></i> Upload Image </button>
              
              <input id="" type="file" class="file-upload" name="image" style="display:none" >
  
            </div>
          </div>


          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Name:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="inputEmail1" placeholder="Name" name="name" value="{{old('name') ?? $dietitian->user->name }}" required>
            </div>
          </div>

          <div class="form-group row">
              <div class="col-sm-2">
                  <label for="username" class="row float-right col-form-label ">User Name:</label>
              </div>
              <div class="col-sm-8">
                  <input type="text" class="form-control" id="username" placeholder="User Name" name="username" value="{{old('username') ?? $dietitian->user->username}}" required readonly>
              </div>
          </div>


          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Email:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="inputEmail1" placeholder="Email" name="email" value="{{old('email') ?? $dietitian->user->email }}" required>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Password:</label>
          </div>
            <div class="col-sm-4">
              <input type="password" class="form-control" id="inputEmail1" placeholder="Password" name="password" >
            </div>

            <div class="col-sm-4">
              <input type="password" class="form-control" id="inputEmail1" placeholder="Confirm Password" name="conf_password">
            </div>
          </div>
        
          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Phone Number:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="inputEmail1" placeholder="Phone Number" name="phone" value="{{old('phone') ?? $dietitian->phone }}" required>
            </div>
          </div>
          

          {{-- <div class="form-group row">
            <div class="col-sm-2">
            <label for="tags" class="row float-right col-form-label ">Tags:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="tags" placeholder="Tags" name="tags" value="{{$dietitian->tags}}" required data-role="tagsinput">
            </div>
          </div> --}}
           

          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Tags:</label>
          </div>
          @php
              $current_tags = $dietitian->user->tags->pluck('id')->toArray();
          @endphp
            <div class="col-sm-8">
                <select  class=" select2bs4" multiple style="width: 100%" id="" placeholder="Tags" name="tags[]" required>
                  @foreach($tags as $tag)
                  <option value="{{$tag->id}}" @if(in_array( $tag->id , $current_tags)) selected @endif > {{$tag->name}} </option>
                  @endforeach
                </select>

            </div>
          </div>



          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Percentage:</label>
          </div>
            <div class="col-sm-4 input-group">
                <input type="number" min="1" max="100" class="form-control" id="inputEmail1" placeholder="Percentage" name="percentage" value="{{$dietitian->percentage}}" required min="1" max="100" onkeyup="check_percentage()" >
                <div class="input-group-append">
                    <div class="input-group-text"><i class="fa fa-percent" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
          </div>
          <p id="percentage-error" class="text-danger" style="display:none; height: 10px; margin-left:17%" >&#x2717 Percentage Should be under 100</p>


          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Portfolio:</label>
          </div>
            <div class="col-sm-8">
              <textarea class="textarea" name="portfolio" placeholder="Portfolio" rows="4" >{{old('portfolio') ?? $dietitian->portfolio}}</textarea>
            </div>
          </div>
          
        
        
        <div>
            <button class="btn btn-primary float-right">Update</button>
        </div>
      </form>
    </div>
    </div>
  
  </div>
</div>

@endsection

@push('script')

    <script>

      function check_percentage(){
        console.log($('#percentage').val())
        if($('#percentage').val() > 100 || $('#percentage').val() < 1 ){
            $('#percentage').css('background-color' , '#ffc7c7');
            $('#signup').prop('disabled' , true);
            $('#percentage-error').show();
        }else{
          $('#percentage').css('background-color' , 'white');
          $('#signup').prop('disabled' , false);
          $('#percentage-error').hide();


        }
      }


      
        var tagnames = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            prefetch: '{{route('tagnames')}}'
        });

        tagnames.initialize();

        $('#tags').tagsinput({
            typeaheadjs: {
                name: 'tagnames',
                displayKey: 'name',
                valueKey: 'name',
                source: tagnames.ttAdapter()
            },
            freeInput : false
        });

    </script>

    @endpush

resources/views/admin/dietitians/index.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" >
    <div class="card ">
      <div class="card-header">
        <h3 class="card-title">Manage Dietitials</h3>
        <a class="btn btn-outline-primary float-right" href="{{route('admin.dietitian.create')}}"> <i class="fas fa-user-cog"></i> Create</a>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <table class="table">
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Email</th>
              <th>Create Date</th>
              <th>Actions</th>
          </tr>
          @if(isset($dietitians))
          @foreach($dietitians as $k => $dietitian)
          <tr>
              <td> {{$k+1}} </td>
              <td> {{$dietitian->user->name}} </td>
              
              <td> {{$dietitian->user->email}} </td>
              
              <td> {{$dietitian->created_at->format('m/d/Y') }} </td>
              <td>
                
                <div class="icheck-success d-inline">
                    <input onchange="change_user_status({{$dietitian->user->id}})" type="checkbox" @if($dietitian->user->status == 1) checked @endif id="checkboxSuccess{{$dietitian->user->id}}">
                    <label for="checkboxSuccess{{$dietitian->user->id}}">
                    </label>
                  </div>

                  <a href="javascript:;" onclick="AskBeforeDelete({{$dietitian->id}})" class="text-danger"  > <i class="fas fa-trash"></i> </a>

                  <a href="{{route('admin.dietitian.edit' , $dietitian->id)}}" > <i class="fas fa-edit"></i> </a>
              </td>

              <form id="delete-form-{{$dietitian->id}}" action="{{route('admin.dietitian.destroy' , $dietitian->id)}}" method="POST" >
                  @csrf
                  @method('DELETE')
              </form>
          </tr>
          @endforeach
          @endif
      </table>
    </div>
    </div>
  
  </div>
</div>

@endsection

@section('scripts')
    <script>
        function AskBeforeDelete(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
              }).then((result) => {
                if (result.value) {
                  
                    $('#delete-form-'+id).submit();
                }
              })
        }

        function change_user_status(id){
            $.ajax({
                url: '{{url("/")}}/change/user/status/'+id,
                success: function (res){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'User Status Has been updated',
                        showConfirmButton: false,
                        timer: 1500
                      })
                }
            }).fail(function(){
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Some Problem occured',
                    showConfirmButton: false,
                    timer: 1500
                  })
            })
        }
    </script>
@endsection