routes/web.php
<?php

use App\EXRX;
use App\User;
use GuzzleHttp\Psr7;
use App\Jobs\SendEmail;
use App\Jobs\SendEmailTest;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Response;
use GuzzleHttp\Exception\RequestException;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('testing' , 'AdminController@notific');

Route::get('/', function () {
    // dd('sad');
    return view('welcome');
    // return redirect()->route('login');
})->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('get/notifications/{user_id}', 'HomeController@getNotifications')->name('get.notifications');


Route::get('/homepage', 'HomeController@homepage')->name('homepage');

Route::group(['prefix' => 'admin' , 'as' => 'admin.', 'middleware'=>['auth','admin']  ], function () {
    Route::get('/' , function(){
            return redirect('/admin/dashboard');
    } );
    Route::get('/dashboard' , 'DashboardController@index' )->name('index');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('dietitian', 'DietitianController');

    Route::resource('coach', 'CoachController');
    
    Route::get('coach/{coach_id}/clients/' , 'CoachController@viewClients' )->name('coach.clients') ;
    Route::get('coach/{coach_id}/client/{clinet_id}/all-packages' , 'CoachController@viewClientPackages' )->name('coach.client.packages') ;

    Route::get('coach/{coach_id}/client/{clinet_id}/package/{package_id}/plan/view' , 'CoachController@viewClientPackagePlan' )->name('coach.client.package.plan.view') ;

    Route::resource('trainer', 'TrainerController');
    Route::resource('questionnaires', 'QuestionnaireController');
    Route::get('questionnaires/{id}/assignedto','QuestionnaireController@assignedto')->name('question.assigned');
    Route::get('questionnaires/{id}/coach/{coach_id}/show','QuestionnaireController@showCoachAnswers')->name('question.coach.show');
    Route::resource('packages', 'PackageController');
    Route::get('packages/{id}/assignedto','PackageController@assignedto')->name('package.assigned');
    Route::resource('tags', 'TagController');
    Route::resource('supplements','SupplementController');
    Route::resource('workouts','WorkoutController');
    Route::get('user/export','UserController@userExport')->name('export.user');

    Route::get('/messages/{reciever?}' , 'DashboardController@showMessages')->name('messages');
    Route::get('/contact' , 'DashboardController@editContactUS')->name('contact');
    Route::post('/contact/update' , 'DashboardController@updateContactUS')->name('contact.update');
    
    
    Route::get('/financial-reports' , 'FinancialReportsController@getReportForAdmin')->name('financial-reports');
    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPayments')->name('financial-reports.filter');

    Route::get('/pay-to-coach/{payment_id}' , 'FinancialReportsController@payToCoach')->name('pay-to-coach');
    Route::get('/remove/pay-to-coach/{payment_id}' , 'FinancialReportsController@removePayToCoach')->name('remove.pay-to-coach');
    


    Route::get('/exports/payments/{client_ids}' , 'FinancialReportsController@exportPayments')->name('export.payments');


    Route::get('/clients/exports/{client_ids}' , 'DashboardController@exportClients')->name('clients.export');

    // Route::get('/dietitian' , 'DietitianController@index' )->name('dietitian');
});



Route::post('/verifyusername', 'UserController@verifyUserName')->name('verify.username');
Route::post('verifyemail','UserController@verifyEmail')->name('verify.email');
Route::get('tagnames','TagController@tagnames')->name('tagnames');

// ajax routes
Route::get('/change/user/status/{user_id}' , 'UserController@changeStatus' );
















Route::get('coach/login' , 'CoachDashboardController@login' )->name('coach.login');

Route::group(['prefix' => 'coach' , 'as' => 'coach.' , 'middleware'=>['auth' , 'coach']   ], function () {
    Route::get('/' , 'CoachDashboardController@index' )->name('index');
    Route::get('profile' , 'CoachDashboardController@showProfile' )->name('profile');
    // Route::get('profile/edit' , 'CoachDashboardController@editProfile' )->name('profile.edit');
    Route::post('profile/update/{id}' , 'CoachDashboardController@updateProfile' )->name('profile.update');

    Route::get('dashboard' , 'CoachDashboardController@index' )->name('dashboard');
    Route::get('packages' , 'CoachDashboardController@showPackages' )->name('packages');
    Route::get('packages/view/{id}' , 'CoachDashboardController@viewPackage' )->name('packages.view');

    Route::get('questionnaires' , 'CoachDashboardController@showQuestionnaires' )->name('questionnaires');
    Route::get('questionnaires/view/{id}' , 'CoachDashboardController@showQuestionnaire' )->name('questionnaires.view');
    Route::post('questionnaires/store-answer/{id}' , 'QuestionnaireController@storeAnswer' )->name('questionnaires.store-answer');
    

    Route::get('manage-clients' , 'CoachDashboardController@showClients' )->name('manage-clients');
    
    Route::get('manage-clients/filter' , 'CoachDashboardController@filterClients' )->name('manage-clients.filter');
    
    Route::get('manage-client/{client_id}/all-packages' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');
    
    
    Route::post('manage-client/{client_id}/handle-client-request' , 'CoachDashboardController@handleClientRequest' )->name('manage-client.handle-client-request');


    Route::get('manage-client/{client_id}/details' , 'CoachDashboardController@showClientDetails' )->name('manage-client.details');

    Route::get('manage-client/{client_id}/package/{package}/create-plan' , 'CoachDashboardController@createClientPlan' )->name('manage-client.package.create-plan');
    
    
    Route::get('manage-client/{client_id}/package/{package}/start-plan' , 'CoachDashboardController@startClientPlan' )->name('manage-client.package.start-plan');
    
    Route::get('/messages/{reciever?}' , 'CoachDashboardController@showMessages')->name('messages');

    Route::get('/view/workout/{id}' , 'CoachDashboardController@showWorkout' )->name('view.workout');


    Route::get('/financial-reports' , 'FinancialReportsController@getReportForCoach')->name('financial-reports');

    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPaymentsCoach')->name('financial-reports.filter');

    Route::get('reviews' , 'CoachDashboardController@showReviews' )->name('reviews');

    Route::resource('client-questionnaires' , 'ClientQuestionnaireController' );
    Route::post('client-questionnaires-update' , 'ClientQuestionnaireController@update' );
    Route::get('client-questionnaires/{questionnaires_id}/assigned-clients' , 'ClientQuestionnaireController@clients' )->name('client-questionnaires.assigned-clients');
    Route::get('client-questionnaires-delete/{questionnaires_id}' , 'ClientQuestionnaireController@destroy');
    
    Route::post('send-questionnaires-client' , 'ClientQuestionnaireController@sendQuestionnaireToClient');
    
    Route::get('client/{client_id}/questionnaires/{questionnaires_id}/show' , 'ClientQuestionnaireController@showAnswer')->name('client.questionnaires.show') ;

    Route::get('get-questionnaires' , 'ClientQuestionnaireController@getQuestionnaires') ;

    // Route::get('manage-client/{client_id}/package/{package}/plan/{plan}' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');


});


Route::get('/exports/clients/{client_ids}/{coach}' , 'HomeController@exportClients')->name('export.clients');











Route::get('local_payment/{plan_id}'  , 'Api\ClientPaymentController@makePayment' )->name('local_payment') ;
Route::get('remove_local_payment/{payment_id}'  , 'Api\ClientPaymentController@removePayment' )->name('remove_local_payment') ;



// Route::get('paypal' ,  'Api\ApiPlanController@PayForPlan2' );
Route::get('sadad' ,  'Api\ApiPlanController@PayWithSadad' );
Route::get('payment' ,  'PaypalPaymentController@braintreePayment' );
// Route::get('paypal' ,  'PaypalPaymentController@payment' );
// Route::get('paypal' ,  'PaypalPaymentController@paywithCreditCard' );
// Route::get('paypal' ,  'PaypalPaymentController@PayumPayment' );
// Route::post('stripe' ,  'Api\ApiPlanController@PayForPlanStripe' );
// Route::post('stripe-mobile' ,  'Api\ApiPlanController@PayForPlanStripe1' );
Route::get('brain' , 'Api\ApiPlanController@make' );


// Route::get('paypal' , 'Api\ApiPlanController@payForPlan2' );
Route::get('paypal_web' , 'Api\ApiPlanController@paypalWeb' );
Route::get('paypal_return' , 'Api\ApiPlanController@paypalReturn' );

// Route::get('paypal' , function(){


//     $gateway = new Braintree\Gateway([
//         'environment' => 'sandbox',
//         'merchantId' => env('BRAINTREE_MERCHANT_ID'),
//         'publicKey' => env('BRAINTREE_PUBLIC_KEY'),
//         'privateKey' => env('BRAINTREE_PRIVATE_KEY')
//     ]);

//     // $clientToken = $gateway->clientToken()->generate([
//     //     "customerId" => 11
//     // ]);
//     $clientToken = $gateway->clientToken()->generate();

//     // dd($clientToken);

//     return view('coach\clients\payment' , compact('clientToken'));
// } );

Route::get("/payment/make" , 'Api\ApiPlanController@make')->name('payment.make');


Route::get('stripe' , 'Api\ApiPlanController@PayForPlanStripe1' );

Route::get('success' , function(){
    dd('success');
});

Route::get('fail' , function(){

resources/views/admin/coaches/client_packages.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="{{ asset('admin-plugins/toastr/toastr.min.css')}}">

@endsection

@section('content')

<div class="row">

   @include('layouts.partials.swals')

   <div class="col-md-12" style="padding:30px" >
    <div class="card ">
      <div class="card-header">
        <h3 class="card-title"> <b> {{$client->name}} </b> Packages</h3>
        {{-- <a class="btn btn-outline-primary float-right" href="{{route('admin.packages.create')}}"> <i class="fas fa-plus"></i> Create</a> --}}
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <table class="table">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Price</th>
            <th>Duration</th>
            <th>Create Date</th>
            <th>Start Date</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
            
            @foreach( $packages as $k => $package)
            <tr>
                <td> {{$k+1}} </td>
                <td> {{$package->name}} </td>
                @if($package->paid)
                    <td>{{$package->price}}$</td>
                @else
                    <td>Free</td>
                @endif
                <td> {{$package->duration}}-Days </td>
  
                {{-- <td><a href="{{route('admin.package.assigned', $package->id)}}"> {{$package->users()->count()}} </a></td> --}}
                <td> {{$package->pivot->created_at->format('m/d/Y') }} </td>
                <td> 

                  @if($package->plans->where('coach_id' , $coach->id )->where('client_id' , $client->id )->first())

                    @if($package->plans->where('coach_id' , $coach->id )->where('client_id' , $client->id )->first()->start_status)
                    {{ $package->plans->where('coach_id' , $coach->id )->where('client_id' , $client->id )->first()->start_date }} 
                    @else
                    Not Started
                    @endif

                    @endif

                </td>
                 <td>

                    @if($package->plans->where('coach_id' , $coach->id )->where('client_id' , $client->id )->first())

                    <a class="btn btn-outline-success btn-sm" href="{{route('admin.coach.client.package.plan.view' , [ $coach->id , $client->id , $package->id] )}} " > <i class="fas fa-info-circle"></i> View</a>
                    @else
                    <a class="btn btn-outline-primary btn-sm" href="#" > <i class="fas fa-info-circle"></i> No Plan</a>
                    @endif
                  </tr>
            </tbody>
            @endforeach

      </table>
    </div>
    </div>
  
  </div>
</div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           {{--  <a id="paypal"></a>   --}}


          <form action="{{url('api/payment_via_paypal')}}" method="POST">
          <input class="form-control" name="card" >
          
            <button type="submit" class="btn btn-success" >PAY</button>
          </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
<script src="{{ asset('admin-plugins/toastr/toastr.min.js')}}"></script>

<script src="https://www.paypal.com/sdk/js?client-id={{env('PAYPAL_CLIENT_ID')}}&currency=USD" data-namespace="paypal_sdk" ></script>

<script>

  paypal_sdk.Buttons({
    createOrder: function(data, actions) {
      // This function sets up the details of the transaction, including the amount and line item details.
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '110.01'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      // This function captures the funds from the transaction.
      return actions.order.capture().then(function(details) {
        // This function shows a transaction success message to your buyer.
        console.log(details)
        //alert('Transaction completed by ' + details.payer.name.given_name);
        axios.post('/api/payment_via_paypal' , {
            all_details: details ,
        }).then( res => {
          
          console.log(res)

          toastr.success('Data Saved successfully.')

        } )
        .catch(errors => { console.log(errors) 
        
          toastr.error(error.response.data.message)
        });
      });
    }
  }).render('#paypal');
  //This function displays Smart Payment Buttons on your web page.

  //paypal_sdk.Buttons().render('#paypal');
</script>


    <script>
        function AskBeforeDelete(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {

                    $('#delete-form-'+id).submit();
                }
            })
        }

        function change_user_status(id){
            $.ajax({
                url: '{{url("/")}}/change/user/status/'+id,
                success: function (res){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'User Status Has been updated',
                        showConfirmButton: false,
                        timer: 1500
                      })
                }
            }).fail(function(){
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Some Problem occured',
                    showConfirmButton: false,
                    timer: 1500
                  })
            })
        }
    </script>
@endsection

resources/views/admin/coaches/clients.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')

   <div class="col-md-12" style="padding:30px" >
    <div class="card ">
      <div class="card-header">
        <h3 class="card-title">{{$coach->user->name}} Clients</h3>
        @if($clients->count() > 0)
        <a class="btn btn-outline-primary float-right" href="{{route('export.clients' , [json_encode($clients->pluck('id')) , $coach->id   ] )}}"> <i class="fas fa-upload"></i> Export</a>
        @endif
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <table class="table">
          <thead>
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Email</th>
              <th>Packages</th>
              {{--  <th>Actions</th>  --}}
          </tr>
          </thead>
          <tbody>
            
          @foreach( $clients as $k => $client)
          <tr>
            <td> {{$k+1}} </td>
            <td> {{$client->name}} </td>
            <td>{{$client->email}}</td>
              
            <td>
            
            <a class="btn btn-outline-primary btn-sm" href="{{route('admin.coach.client.packages' , [ $coach->id ,  $client->id])}} " > <i class="fas fa-eye"></i> {{ $client->subscribed_packages->where('pivot.coach_id' , $coach->id)->count() }}</a>
            </td>
            
            {{--  <td>
            <a class="btn btn-outline-primary btn-sm" href="{{route('coach.packages.view' , $client->id)}} " > <i class="fas fa-eye"></i> View</a>
            </td>  --}}
             
          </tr>
          </tbody>
          @endforeach
      </table>
    </div>
    </div>
  
  </div>
</div>

@endsection

@section('scripts')
    <script>
        function AskBeforeDelete(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {

                    $('#delete-form-'+id).submit();
                }
            })
        }

        function change_user_status(id){
            $.ajax({
                url: '{{url("/")}}/change/user/status/'+id,
                success: function (res){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'User Status Has been updated',
                        showConfirmButton: false,
                        timer: 1500
                      })
                }
            }).fail(function(){
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Some Problem occured',
                    showConfirmButton: false,
                    timer: 1500
                  })
            })
        }
    </script>
@endsection

resources/views/admin/coaches/index.blade.php
@extends('layouts.dashboard')


@section('content')

@php
    $trainers = $coaches->where('role' , 3);
    $dietitians = $coaches->where('role' , 4);
@endphp

<div class="row">

   @include('layouts.partials.swals')

   <div class="col-12 col-sm-12 col-lg-12" style="padding:30px">
    <div class="card-header">
        <h3 class="card-title">Manage Coaches</h3>
        <a class="btn btn-outline-primary float-right" href="{{route('admin.coach.create')}}"> <i class="fas fa-user-cog"></i> Create</a>
      </div>

    <div class="card card-info card-tabs">
      <div class="card-header p-0 pt-1">
        <ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
          <li class="nav-item" style="width:50%;">
            <a class="nav-link active" id="custom-tabs-one-home-tab" data-toggle="pill" href="#custom-tabs-one-home" role="tab" aria-controls="custom-tabs-one-home" aria-selected="true">Trainers</a>
          </li>
          <li class="nav-item" style="width:50%;">
            <a class="nav-link" id="custom-tabs-one-profile-tab" data-toggle="pill" href="#custom-tabs-one-profile" role="tab" aria-controls="custom-tabs-one-profile" aria-selected="false">Dietitians</a>
          </li>
    
        </ul>
      </div>
      <div class="card-body">
        <div class="tab-content" id="custom-tabs-one-tabContent">
          <div class="tab-pane fade show active" id="custom-tabs-one-home" role="tabpanel" aria-labelledby="custom-tabs-one-home-tab">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Create Date</th>
                    <th>Actions</th>
                </tr>
                @if(isset($trainers))
                @foreach($trainers as $k => $coach)
                <tr id="coach-list">
                    <td> {{$k+1}} </td>
                    <td> {{$coach->user->name}} </td>

                    <td> <img class="profile-picture" src="@if($coach->user->photo) {{asset('images/profile_images/'.$coach->user->photo)}} @else {{asset('img/no-image-found.jpg')}} @endif"> </td>

                    <td> {{$coach->user->username}} </td>

                    <td> {{$coach->user->email}} </td>
                    
                    <td> {{$coach->created_at->format('m/d/Y') }} </td>
                    <td>
                      
                      <div class="icheck-success d-inline">
                          <input onchange="change_user_status({{$coach->user->id}})" type="checkbox" @if($coach->user->status == 1) checked @endif id="checkboxSuccess{{$coach->user->id}}">
                          <label for="checkboxSuccess{{$coach->user->id}}">
                          </label>
                        </div>
      
                        <a href="{{route('admin.coach.edit' , $coach->id)}}" > <i class="fas fa-edit"></i> </a>

                        <a href="{{route('admin.coach.show' , $coach->id)}}" class="text-info" > <i class="fas fa-eye" title="View Profile" ></i> </a>

                        <a href="javascript:;" onclick="AskBeforeDelete({{$coach->id}})" class="text-danger"  > <i class="fas fa-trash"></i> </a>
      

                        <a href="{{route('admin.coach.clients' , $coach->id)}}" class="text-success" title="View Clients" > <i class="fas fa-list"></i> </a>
                    </td>
      
                    <form id="delete-form-{{$coach->id}}" action="{{route('admin.coach.destroy' , $coach->id)}}" method="POST" >
                        @csrf
                        @method('DELETE')
                    </form>
                </tr>
                @endforeach
                @endif
            </table>          </div>
          <div class="tab-pane fade" id="custom-tabs-one-profile" role="tabpanel" aria-labelledby="custom-tabs-one-profile-tab">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Profile Image</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Create Date</th>
                    <th>Actions</th>
                </tr>
                @if(isset($dietitians))
                @foreach($dietitians as $k => $coach)
                <tr id="coach-list">
                    <td> {{$k+1}} </td>
                    <td> {{$coach->user->name}} </td>

                    <td> <img class="profile-picture" src="@if($coach->user->photo) {{asset('images/profile_images/'.$coach->user->photo)}} @else {{asset('img/no-image-found.jpg')}} @endif"> </td>

                    <td> {{$coach->user->username}} </td>

                    
                    <td> {{$coach->user->email}} </td>
                    
                    <td> {{$coach->created_at->format('m/d/Y') }} </td>
                    <td>
                      
                      <div class="icheck-success d-inline">
                          <input onchange="change_user_status({{$coach->user->id}})" type="checkbox" @if($coach->user->status == 1) checked @endif id="checkboxSuccess{{$coach->user->id}}">
                          <label for="checkboxSuccess{{$coach->user->id}}">
                          </label>
                        </div>
                        <a href="{{route('admin.coach.edit' , $coach->id)}}" > <i class="fas fa-edit"></i> </a>

                        <a href="{{route('admin.coach.show' , $coach->id)}}" class="text-info" > <i class="fas fa-eye" title="View Profile" ></i> </a>

                        <a href="javascript:;" onclick="AskBeforeDelete({{$coach->id}})" class="text-danger"  > <i class="fas fa-trash"></i> </a>
      

                        <a href="{{route('admin.coach.clients' , $coach->id)}}" class="text-success" title="View Clients" > <i class="fas fa-list"></i> </a>
                
                    </td>
      
                    <form id="delete-form-{{$coach->id}}" action="{{route('admin.coach.destroy' , $coach->id)}}" method="POST" >
                        @csrf
                        @method('DELETE')
                    </form>
                </tr>
                @endforeach
                @endif
            </table>
        </div>
          
        </div>
      </div>
      <!-- /.card -->
    </div>
  </div>

{{-- <div class="col-md-12" style="padding:30px" >
    <div class="card ">
      <div class="card-header">
        <h3 class="card-title">Manage Coaches</h3>
        <a class="btn btn-outline-primary float-right" href="{{route('admin.coach.create')}}"> <i class="fas fa-user-cog"></i> Create</a>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >

        
      <table class="table">
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Email</th>
              <th>Create Date</th>
              <th>Actions</th>
          </tr>
          @if(isset($coaches))
          @foreach($coaches as $k => $coach)
          <tr>
              <td> {{$k+1}} </td>
              <td> {{$coach->user->name}} </td>
              
              <td> {{$coach->user->email}} </td>
              
              <td> {{$coach->created_at->format('m/d/Y') }} </td>
              <td>
                
                <div class="icheck-success d-inline">
                    <input onchange="change_user_status({{$coach->user->id}})" type="checkbox" @if($coach->user->status == 1) checked @endif id="checkboxSuccess{{$coach->user->id}}">
                    <label for="checkboxSuccess{{$coach->user->id}}">
                    </label>
                  </div>

                  <a href="javascript:;" onclick="AskBeforeDelete({{$coach->id}})" class="text-danger"  > <i class="fas fa-trash"></i> </a>

                  <a href="{{route('admin.coach.edit' , $coach->id)}}" > <i class="fas fa-edit"></i> </a>
              </td>

              <form id="delete-form-{{$coach->id}}" action="{{route('admin.coach.destroy' , $coach->id)}}" method="POST" >
                  @csrf
                  @method('DELETE')
              </form>
          </tr>
          @endforeach
          @endif
      </table>
    </div>
    </div>
  
  </div> --}}
</div>

@endsection

@section('scripts')
    <script>
        function AskBeforeDelete(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
              }).then((result) => {
                if (result.value) {
                  
                    $('#delete-form-'+id).submit();
                }
              })
        }

        function change_user_status(id){
            $.ajax({
                url: '{{url("/")}}/change/user/status/'+id,
                success: function (res){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'User Status Has been updated',
                        showConfirmButton: false,
                        timer: 1500
                      })
                }
            }).fail(function(){
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Some Problem occured',
                    showConfirmButton: false,
                    timer: 1500
                  })
            })
        }
    </script>
@endsection