routes/web.php
<?php

use App\EXRX;
use App\User;
use GuzzleHttp\Psr7;
use App\Jobs\SendEmail;
use App\Jobs\SendEmailTest;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Response;
use GuzzleHttp\Exception\RequestException;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('testing' , 'AdminController@notific');

Route::get('/', function () {
    // dd('sad');
    return view('welcome');
    // return redirect()->route('login');
})->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('get/notifications/{user_id}', 'HomeController@getNotifications')->name('get.notifications');


Route::get('/homepage', 'HomeController@homepage')->name('homepage');

Route::group(['prefix' => 'admin' , 'as' => 'admin.', 'middleware'=>['auth','admin']  ], function () {
    Route::get('/' , function(){
            return redirect('/admin/dashboard');
    } );
    Route::get('/dashboard' , 'DashboardController@index' )->name('index');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('dietitian', 'DietitianController');

    Route::resource('coach', 'CoachController');
    
    Route::get('coach/{coach_id}/clients/' , 'CoachController@viewClients' )->name('coach.clients') ;
    Route::get('coach/{coach_id}/client/{clinet_id}/all-packages' , 'CoachController@viewClientPackages' )->name('coach.client.packages') ;

    Route::get('coach/{coach_id}/client/{clinet_id}/package/{package_id}/plan/view' , 'CoachController@viewClientPackagePlan' )->name('coach.client.package.plan.view') ;

    Route::resource('trainer', 'TrainerController');
    Route::resource('questionnaires', 'QuestionnaireController');
    Route::get('questionnaires/{id}/assignedto','QuestionnaireController@assignedto')->name('question.assigned');
    Route::get('questionnaires/{id}/coach/{coach_id}/show','QuestionnaireController@showCoachAnswers')->name('question.coach.show');
    Route::resource('packages', 'PackageController');
    Route::get('packages/{id}/assignedto','PackageController@assignedto')->name('package.assigned');
    Route::resource('tags', 'TagController');
    Route::resource('supplements','SupplementController');
    Route::resource('workouts','WorkoutController');
    Route::get('user/export','UserController@userExport')->name('export.user');

    Route::get('/messages/{reciever?}' , 'DashboardController@showMessages')->name('messages');
    Route::get('/contact' , 'DashboardController@editContactUS')->name('contact');
    Route::post('/contact/update' , 'DashboardController@updateContactUS')->name('contact.update');
    
    
    Route::get('/financial-reports' , 'FinancialReportsController@getReportForAdmin')->name('financial-reports');
    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPayments')->name('financial-reports.filter');

    Route::get('/pay-to-coach/{payment_id}' , 'FinancialReportsController@payToCoach')->name('pay-to-coach');
    Route::get('/remove/pay-to-coach/{payment_id}' , 'FinancialReportsController@removePayToCoach')->name('remove.pay-to-coach');
    


    Route::get('/exports/payments/{client_ids}' , 'FinancialReportsController@exportPayments')->name('export.payments');


    Route::get('/clients/exports/{client_ids}' , 'DashboardController@exportClients')->name('clients.export');

    // Route::get('/dietitian' , 'DietitianController@index' )->name('dietitian');
});



Route::post('/verifyusername', 'UserController@verifyUserName')->name('verify.username');
Route::post('verifyemail','UserController@verifyEmail')->name('verify.email');
Route::get('tagnames','TagController@tagnames')->name('tagnames');

// ajax routes
Route::get('/change/user/status/{user_id}' , 'UserController@changeStatus' );
















Route::get('coach/login' , 'CoachDashboardController@login' )->name('coach.login');

Route::group(['prefix' => 'coach' , 'as' => 'coach.' , 'middleware'=>['auth' , 'coach']   ], function () {
    Route::get('/' , 'CoachDashboardController@index' )->name('index');
    Route::get('profile' , 'CoachDashboardController@showProfile' )->name('profile');
    // Route::get('profile/edit' , 'CoachDashboardController@editProfile' )->name('profile.edit');
    Route::post('profile/update/{id}' , 'CoachDashboardController@updateProfile' )->name('profile.update');

    Route::get('dashboard' , 'CoachDashboardController@index' )->name('dashboard');
    Route::get('packages' , 'CoachDashboardController@showPackages' )->name('packages');
    Route::get('packages/view/{id}' , 'CoachDashboardController@viewPackage' )->name('packages.view');

    Route::get('questionnaires' , 'CoachDashboardController@showQuestionnaires' )->name('questionnaires');
    Route::get('questionnaires/view/{id}' , 'CoachDashboardController@showQuestionnaire' )->name('questionnaires.view');
    Route::post('questionnaires/store-answer/{id}' , 'QuestionnaireController@storeAnswer' )->name('questionnaires.store-answer');
    

    Route::get('manage-clients' , 'CoachDashboardController@showClients' )->name('manage-clients');
    
    Route::get('manage-clients/filter' , 'CoachDashboardController@filterClients' )->name('manage-clients.filter');
    
    Route::get('manage-client/{client_id}/all-packages' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');
    
    
    Route::post('manage-client/{client_id}/handle-client-request' , 'CoachDashboardController@handleClientRequest' )->name('manage-client.handle-client-request');


    Route::get('manage-client/{client_id}/details' , 'CoachDashboardController@showClientDetails' )->name('manage-client.details');

    Route::get('manage-client/{client_id}/package/{package}/create-plan' , 'CoachDashboardController@createClientPlan' )->name('manage-client.package.create-plan');
    
    
    Route::get('manage-client/{client_id}/package/{package}/start-plan' , 'CoachDashboardController@startClientPlan' )->name('manage-client.package.start-plan');
    
    Route::get('/messages/{reciever?}' , 'CoachDashboardController@showMessages')->name('messages');

    Route::get('/view/workout/{id}' , 'CoachDashboardController@showWorkout' )->name('view.workout');


    Route::get('/financial-reports' , 'FinancialReportsController@getReportForCoach')->name('financial-reports');

    Route::get('/financial-reports/filter' , 'FinancialReportsController@filterPaymentsCoach')->name('financial-reports.filter');

    Route::get('reviews' , 'CoachDashboardController@showReviews' )->name('reviews');

    Route::resource('client-questionnaires' , 'ClientQuestionnaireController' );
    Route::post('client-questionnaires-update' , 'ClientQuestionnaireController@update' );
    Route::get('client-questionnaires/{questionnaires_id}/assigned-clients' , 'ClientQuestionnaireController@clients' )->name('client-questionnaires.assigned-clients');
    Route::get('client-questionnaires-delete/{questionnaires_id}' , 'ClientQuestionnaireController@destroy');
    
    Route::post('send-questionnaires-client' , 'ClientQuestionnaireController@sendQuestionnaireToClient');
    
    Route::get('client/{client_id}/questionnaires/{questionnaires_id}/show' , 'ClientQuestionnaireController@showAnswer')->name('client.questionnaires.show') ;

    Route::get('get-questionnaires' , 'ClientQuestionnaireController@getQuestionnaires') ;

    // Route::get('manage-client/{client_id}/package/{package}/plan/{plan}' , 'CoachDashboardController@showClientPackages' )->name('manage-client.packages');


});


Route::get('/exports/clients/{client_ids}/{coach}' , 'HomeController@exportClients')->name('export.clients');











Route::get('local_payment/{plan_id}'  , 'Api\ClientPaymentController@makePayment' )->name('local_payment') ;
Route::get('remove_local_payment/{payment_id}'  , 'Api\ClientPaymentController@removePayment' )->name('remove_local_payment') ;



// Route::get('paypal' ,  'Api\ApiPlanController@PayForPlan2' );
Route::get('sadad' ,  'Api\ApiPlanController@PayWithSadad' );
Route::get('payment' ,  'PaypalPaymentController@braintreePayment' );
// Route::get('paypal' ,  'PaypalPaymentController@payment' );
// Route::get('paypal' ,  'PaypalPaymentController@paywithCreditCard' );
// Route::get('paypal' ,  'PaypalPaymentController@PayumPayment' );
// Route::post('stripe' ,  'Api\ApiPlanController@PayForPlanStripe' );
// Route::post('stripe-mobile' ,  'Api\ApiPlanController@PayForPlanStripe1' );
Route::get('brain' , 'Api\ApiPlanController@make' );


// Route::get('paypal' , 'Api\ApiPlanController@payForPlan2' );
Route::get('paypal_web' , 'Api\ApiPlanController@paypalWeb' );
Route::get('paypal_return' , 'Api\ApiPlanController@paypalReturn' );

// Route::get('paypal' , function(){


//     $gateway = new Braintree\Gateway([
//         'environment' => 'sandbox',
//         'merchantId' => env('BRAINTREE_MERCHANT_ID'),
//         'publicKey' => env('BRAINTREE_PUBLIC_KEY'),
//         'privateKey' => env('BRAINTREE_PRIVATE_KEY')
//     ]);

//     // $clientToken = $gateway->clientToken()->generate([
//     //     "customerId" => 11
//     // ]);
//     $clientToken = $gateway->clientToken()->generate();

//     // dd($clientToken);

//     return view('coach\clients\payment' , compact('clientToken'));
// } );

Route::get("/payment/make" , 'Api\ApiPlanController@make')->name('payment.make');


Route::get('stripe' , 'Api\ApiPlanController@PayForPlanStripe1' );

Route::get('success' , function(){
    dd('success');
});

Route::get('fail' , function(){

resources/views/admin/admins/create.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" >
    <div class="card card-info ">
      <div class="card-header">
        <h3 class="card-title">Create New Admin</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <form action="{{route('admin.admins.store')}}" method="POST" enctype="multipart/form-data">
          @include('layouts.partials.form_errors')
          @csrf

          <div class="form-group row">
            <div class="col-sm-2">
          </div>
            <div class="col-sm-8">
  
              <img id="image" src="{{asset('img/no-image-found.jpg')}}" class="profile-image" />
  
              <button type="button" class="btn btn-outline-success" id="upload-button"> <i class="fas fa-image"></i> Upload Image </button>
              
              <input id="" type="file" class="file-upload" name="image" style="display:none" >
  
            </div>
          </div>
  

          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Name:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="inputEmail1" placeholder="Name" name="name" value="{{old('name')}}" required>
            </div>
          </div>

          <div class="form-group row">
              <div class="col-sm-2">
                  <label for="username" class="row float-right col-form-label ">User Name:</label>
              </div>
              <div class="col-sm-8">
                  <input type="text" class="form-control" id="username" placeholder="User Name" name="username" value="{{old('username')}}" required >
                  <div >
                      <p id="username-error" class="text-danger" style="display:none; height: 10px" >&#x2717 username not available</p>
                      <p id="username-success" class="text-success" style="display:none; height: 10px" >&#x2713 username is available</p>
                  </div>

              </div>

          </div>

          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail2" class="row float-right col-form-label ">Email:</label>
          </div>
            <div class="col-sm-8">
              <input type="email" class="form-control" id="email" placeholder="Email" name="email" value="{{old('email')}}" required>
                <div>
                    <p id="email-error" class="text-danger" style="display:none; height: 10px" >&#x2717 email not available</p>
                    <p id="email-success" class="text-success" style="display:none; height: 10px" >&#x2713 email is available</p>
                </div>

            </div>
          </div>
          
          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail3" class="row float-right col-form-label ">Password:</label>
          </div>
            <div class="col-sm-8">
              <input type="password" class="form-control" id="inputEmail3" placeholder="Password" name="password" autocomplete="off" required>
            </div>
          </div>
          
          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail4" class="row float-right col-form-label ">Confirm Password:</label>
          </div>
            <div class="col-sm-8">
              <input type="password" class="form-control" id="inputEmail4" placeholder="Confirm Password" name="conf_password" autocomplete="off" required>
            </div>
          </div>
          

        
        <div>
            <button id="signup" class="btn btn-primary float-right">Create</button>
        </div>
      </form>
    </div>
    </div>
  
  </div>
</div>

@endsection

@push('script')

<script>

    $(document).ready(function () {
        var isValid = true;
        var usernameerror = false;
        var emailerror = false;



        jQuery('#username').keyup(function (e) {


            e.preventDefault();
            var username = $('#username').val();
            $.ajaxSetup({
                headers:{
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            jQuery.ajax({
                url: "{{route('verify.username')}}",
                method: 'POST',
                data:{
                    username: username,
                },
                success: function (result) {
                    console.log(result)
                    if($('#username').val().length>0){
                        if(result == 1){
                            $('#username-success').hide();
                            $('#username-error').show();
                            usernameerror = true;

                            if(!isValid || ( usernameerror ||  emailerror ) )
                            {
                                $('#signup').prop('disabled', true)
                            }
                        }
                        else {
                            $('#username-success').show();
                            $('#username-error').hide();
                            usernameerror = false;

                            if(isValid && (!usernameerror && !emailerror)){
                                $('#signup').prop('disabled', false);
                            }
                        }
                    }

                    else {
                        $('#username-success').hide();
                        $('#username-error').hide();
                        usernameerror = false;
                    }


                }


            });


        })


        jQuery('#email').keyup(function (e) {


            e.preventDefault();
            var email = $('#email').val();
            $.ajaxSetup({
                headers:{
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            jQuery.ajax({
                url: "{{route('verify.email')}}",
                method: 'POST',
                data:{
                    email: email,
                },
                success: function (result) {
                    console.log(result)
                    if($('#email').val().length>0){
                        if(result == 1){
                            $('#email-success').hide();
                            $('#email-error').show();
                            emailerror = true;

                            if(!isValid || ( usernameerror ||  emailerror ) )
                            {
                                $('#signup').prop('disabled', true)
                            }
                        }
                        else {
                            $('#email-success').show();
                            $('#email-error').hide();
                            emailerror = false;

                            if(isValid && (!usernameerror && !emailerror)){
                                $('#signup').prop('disabled', false);
                            }
                        }
                    }

                    else {
                        $('#email-success').hide();
                        $('#email-error').hide();
                        emailerror = false;
                    }


                }


            });


        })


    });




</script>
    @endpush

resources/views/admin/admins/edit.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">


<div class="col-md-12" style="padding:30px" >
    <div class="card card-info ">
      <div class="card-header">
        <h3 class="card-title">Update User</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <form action="{{route('admin.admins.update' , $user->id)}}" method="POST" enctype="multipart/form-data">
        @include('layouts.partials.form_errors')
        @csrf
        @method('PATCH')

        <div class="form-group row">
          <div class="col-sm-2">
        </div>
          <div class="col-sm-8">

            <img id="image" src="@if($user->photo) {{asset('images/profile_images/'.$user->photo)}} @else {{asset('img/no-image-found.jpg')}} @endif" class="profile-image" />

            <button type="button" class="btn btn-outline-success" id="upload-button"> <i class="fas fa-image"></i> Upload Image </button>
            
            <input id="" type="file" class="file-upload" name="image" style="display:none" >

          </div>
        </div>



          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail1" class="row float-right col-form-label ">Name:</label>
          </div>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="inputEmail1" placeholder="Name" name="name" value="{{old('name') ?? $user->name }}" required>
            </div>
          </div>

          <div class="form-group row">
              <div class="col-sm-2">
                  <label for="username" class="row float-right col-form-label ">User Name:</label>
              </div>
              <div class="col-sm-8">
                  <input type="text" class="form-control" id="username" placeholder="User Name" name="username" value="{{old('username') ?? $user->username}}" required disabled>
              </div>
          </div>


          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail2" class="row float-right col-form-label ">Email:</label>
          </div>
            <div class="col-sm-8">
              <input type="email" class="form-control" id="inputEmail2" placeholder="Email" name="email" value="{{old('email') ?? $user->email }}" required>
            </div>
          </div>
          
          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail3" class="row float-right col-form-label ">Password:</label>
          </div>
            <div class="col-sm-8">
              <input type="password" class="form-control" id="inputEmail3" placeholder="Password" name="password" autocomplete="off" >
            </div>
          </div>
          
          <div class="form-group row">
            <div class="col-sm-2">
            <label for="inputEmail4" class="row float-right col-form-label ">Confirm Password:</label>
          </div>
            <div class="col-sm-8">
              <input type="password" class="form-control" id="inputEmail4" placeholder="Confirm Password" name="conf_password" autocomplete="off" >
            </div>
          </div>
          

        
        <div>
            <button class="btn btn-primary float-right">Update</button>
        </div>
      </form>
    </div>
    </div>
  
  </div>
</div>

@endsection

resources/views/admin/admins/index.blade.php
@extends('layouts.dashboard')


@section('content')


<div class="row">

   @include('layouts.partials.swals')

<div class="col-md-12" style="padding:30px" >
    <div class="card ">
      <div class="card-header">
        <h3 class="card-title">Manage Admins</h3>
        <a class="btn btn-outline-primary float-right" href="{{route('admin.admins.create')}}"> <i class="fas fa-user-cog"></i> Create</a>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <table class="table">
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Usernmae</th>
              <th>Email</th>
              <th>Create Date</th>
              <th>Actions</th>
          </tr>

          @foreach($users as $k => $user)
          <tr>
              <td> {{$k+1}} </td>
              <td> {{$user->name}} </td>
              <td> {{$user->username}} </td>
              <td> {{$user->email}} </td>
              <td> {{$user->created_at->toDateString()}} </td>
              <td>
                
                <div class="icheck-success d-inline">
                    <input onchange="change_user_status({{$user->id}})" type="checkbox" @if($user->status == 1) checked @endif id="checkboxSuccess{{$user->id}}">
                    <label for="checkboxSuccess{{$user->id}}">
                    </label>
                  </div>

                  <a href="javascript:;" onclick="AskBeforeDelete({{$user->id}})" class="text-danger"  > <i class="fas fa-trash"></i> </a>

                  <a href="{{route('admin.admins.edit' , $user->id)}}" > <i class="fas fa-edit"></i> </a>
              </td>

              <form id="delete-form-{{$user->id}}" action="{{route('admin.admins.destroy' , $user->id)}}" method="POST" >
                  @csrf
                  @method('DELETE')
              </form>
          </tr>
          @endforeach
      </table>
    </div>
    </div>
  
  </div>
</div>

@endsection

@section('scripts')
    <script>
        function AskBeforeDelete(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
              }).then((result) => {
                if (result.value) {
                  
                    $('#delete-form-'+id).submit();
                }
              })
        }

        function change_user_status(id){
            $.ajax({
                url: '{{url("/")}}/change/user/status/'+id,
                success: function (res){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'User Status Has been updated',
                        showConfirmButton: false,
                        timer: 1500
                      })
                }
            }).fail(function(){
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Some Problem occured',
                    showConfirmButton: false,
                    timer: 1500
                  })
            })
        }
    </script>
@endsection